import pandas as pd
import numpy as np
rice = pd.read_csv("finalRice.csv", encoding='latin-1', low_memory=False, sep=",") 

rice['africa'] = np.where((rice.adm0_name == "Afghanistan") 
                        | (rice.adm0_name == "Algeria")
                        | (rice.adm0_name == "Chad")
                        | (rice.adm0_name == "Egypt")
                        | (rice.adm0_name == "Mauritania")
                        | (rice.adm0_name == "Benin")
                        | (rice.adm0_name == "Burkina Faso")
                        | (rice.adm0_name == "Burundi")
                        | (rice.adm0_name == "Cameroon")
                        | (rice.adm0_name == "Cape Verde")
                        | (rice.adm0_name == "Central African Republic")
                        | (rice.adm0_name == "Democratic Republic of the Congo")
                        | (rice.adm0_name == "Cote d'Ivore")
                        | (rice.adm0_name == "Djibouti")
                        | (rice.adm0_name == "Ethiopia")
                        | (rice.adm0_name == "Congo")
                        | (rice.adm0_name == "Gambia")
                        | (rice.adm0_name == "Ghana")
                        | (rice.adm0_name == "Guinea-Bissau")
                        | (rice.adm0_name == "Guinea")
                        | (rice.adm0_name == "Kenya")
                        | (rice.adm0_name == "Lesotho")
                        | (rice.adm0_name == "Liberia")
                        | (rice.adm0_name == "Madagascar")
                        | (rice.adm0_name == "Malawi")
                        | (rice.adm0_name == "Mali")
                        | (rice.adm0_name == "Mozambique")
                        | (rice.adm0_name == "Niger")
                        | (rice.adm0_name == "Nigeria")
                        | (rice.adm0_name == "Rwanda")
                        | (rice.adm0_name == "Senegal")
                        | (rice.adm0_name == "Somalia")
                        | (rice.adm0_name == "Swaziland")
                        | (rice.adm0_name == "Uganda")
                        | (rice.adm0_name == "Tanzania")
                        | (rice.adm0_name == "Zambia")
                        | (rice.adm0_name == "Zimbabwe")
                        | (rice.adm0_name == "Sudan")
                        | (rice.adm0_name == "South Sudan"), 1, 0)
rice['asia'] = np.where((rice.adm0_name == "Bangladesh")
                        | (rice.adm0_name == "Bhutan")
                        | (rice.adm0_name == "Cambodia")
                        | (rice.adm0_name == "India")
                        | (rice.adm0_name == "Indonesia")
                        | (rice.adm0_name == "Lao People's Democratic Republic")
                        | (rice.adm0_name == "Myanmar")
                        | (rice.adm0_name == "Nepal")
                        | (rice.adm0_name == "Pakistan")
                        | (rice.adm0_name == "Philippines")
                        | (rice.adm0_name == "Sri Lanka")
                        | (rice.adm0_name == "Timor-Leste")
                        | (rice.adm0_name == "Iran  (Islamic Republic of)")
                        | (rice.adm0_name == "Iraq")
                        | (rice.adm0_name == "Jordan")
                        | (rice.adm0_name == "Kyrgyzstan")
                        | (rice.adm0_name == "Lebanon")
                        | (rice.adm0_name == "Syrian Arab Republic")
                        | (rice.adm0_name == "Tajikistan")
                        | (rice.adm0_name == "Yemen")
                        | (rice.adm0_name == "State of Palestine"), 1, 0)
rice['south_america'] = np.where((rice.adm0_name == "Bolivia")
                        | (rice.adm0_name == "Colombia")
                        | (rice.adm0_name == "Peru"), 1, 0)
rice['north_america'] = np.where((rice.adm0_name == "Costa Rica")
                        | (rice.adm0_name == "El Salvador")
                        | (rice.adm0_name == "Guatemala")
                        | (rice.adm0_name == "Haiti")
                        | (rice.adm0_name == "Honduras")
                        | (rice.adm0_name == "Panama"), 1, 0)